apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-service
  namespace: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-service
  template:
    metadata:
      labels:
        app: alerting-service
    spec:
      containers:
        - name: alerting-service
          image: digtranza/alerting-service:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: alerting-service
  namespace: devops-monitoring
spec:
  selector:
    app: alerting-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
  template:
    spec:
      containers:
        - image: digtranza/alerting-service:latest
