apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-service
  namespace: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-service
  template:
    metadata:
      labels:
        app: logs-service
    spec:
      containers:
        - name: logs-service
          image: digtranza/logs-service:37
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logs-service
  namespace: devops-monitoring
spec:
  selector:
    app: logs-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

