apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service
  namespace: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-service
  template:
    metadata:
      labels:
        app: metrics-service
    spec:
      containers:
        - name: metrics-service
          image: digtranza/metrics-service:41
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: devops-monitoring
spec:
  selector:
    app: metrics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

