apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-backend
  namespace: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-backend
  template:
    metadata:
      labels:
        app: visualization-backend
    spec:
      containers:
        - name: visualization-backend
          image: digtranza/visualization-backend:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: visualization-backend
  namespace: devops-monitoring
spec:
  selector:
    app: visualization-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
