apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-ui
  namespace: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-ui
  template:
    metadata:
      labels:
        app: visualization-ui
    spec:
      containers:
        - name: visualization-ui
          image: digtranza/visualization-ui:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: visualization-ui
  namespace: devops-monitoring
spec:
  selector:
    app: visualization-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
