name: Logs Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'logs-service/**'
      - 'manifests/logs-service.yaml'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Build Number
        id: buildnum
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ github.token }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        working-directory: ./logs-service
        run: go build -o bin/

      - name: Docker Operations
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ steps.buildnum.outputs.build_number }} ./logs-service/
          docker push ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ steps.buildnum.outputs.build_number }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ steps.buildnum.outputs.build_number }} ${{ secrets.DOCKER_USERNAME }}/logs-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/logs-service:latest

      - name: Update and Push Manifest
        run: |
          sed -i 's|image: .*/logs-service:.*|image: ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ steps.buildnum.outputs.build_number }}|g' manifests/logs-service.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/logs-service.yaml
          git commit -m "CI: Updated logs-service image to build ${{ steps.buildnum.outputs.build_number }}"
          git push