name: Logs Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'logs-service/**'
      - 'manifests/logs-service.yaml'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Debug Checkout
        run: |
          ls -la logs-service/
          ls -la logs-service/app/

      - name: Debug Go Environment
        working-directory: ./logs-service
        run: |
          pwd
          ls -la
          ls -la app/
          cat go.mod
          go env | grep -E 'GOPATH|GOMOD|GOROOT'

      - name: Verify Go Module
        working-directory: ./logs-service
        run: |
          go mod tidy
          go mod download
          go mod verify

      - name: Build Application
        working-directory: ./logs-service
        env:
          GO111MODULE: "on"
        run: |
          mkdir -p bin
          go build -v -o bin/logs-service ./main.go

      - name: Docker Operations
        working-directory: ./logs-service
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ github.run_number }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/logs-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/logs-service:latest

      - name: Update Kubernetes Manifest
        run: |
          sed -i 's|image: .*/logs-service:.*|image: ${{ secrets.DOCKER_USERNAME }}/logs-service:${{ github.run_number }}|g' manifests/logs-service.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/logs-service.yaml
          git commit -m "CI: Updated logs-service to build ${{ github.run_number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}