name: Metrics Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'metrics-service/**'
      - 'manifests/metrics-service.yaml'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('metrics-service/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        working-directory: ./metrics-service
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./metrics-service
        run: pytest tests/

      - name: Docker Operations
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest || true
          docker build --cache-from=${{ secrets.DOCKER_USERNAME }}/metrics-service:latest -t ${{ secrets.DOCKER_USERNAME }}/metrics-service:${{ github.run_number }} ./metrics-service/
          docker push ${{ secrets.DOCKER_USERNAME }}/metrics-service:${{ github.run_number }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/metrics-service:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest

      - name: Update Kubernetes Manifest
        run: |
          sed -i 's|image: .*/metrics-service:.*|image: ${{ secrets.DOCKER_USERNAME }}/metrics-service:${{ github.run_number }}|g' manifests/metrics-service.yaml
          git add manifests/metrics-service.yaml
          git commit -m "CI: Updated metrics-service to build ${{ github.run_number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}