name: Mirror to GitLab
on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full clone to prevent shallow update errors

      - name: Push to GitLab
        run: |
          git remote remove gitlab || true  # Remove existing remote if it exists
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jerryben/DevOps-Monitoring-Microservices.git
          git push --force gitlab main
