---
name: Mirror to GitLab
on: [push]
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full clone to prevent shallow update errors

      - name: Push to GitLab
        run: |
          git remote remove gitlab || true  # Remove existing remote if it exists
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jerryben/DevOps-Monitoring-Microservices.git
          git push --force gitlab main



# name: Mirror to GitLab

# on:
#   push:
#     branches: [ main ]

# jobs:
#   mirror-to-gitlab:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Push to GitLab
#         if: contains(github.event.head_commit.modified, 'alerting-service/')
#         run: |
#           git remote remove gitlab || true
#           git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jerryben/DevOps-Monitoring-Microservices.git
#           git push gitlab main
